name: 🛠

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'v[0-9]+.x'
  pull_request:
    branches:
      - main
      - 'v[0-9]+.x'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          node-version: '22'

      - name: Run checks
        run: |
          pnpm test
